#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_LINE_LENGTH 81
#define MAX_LABEL_NAME_LENGTH 31
#define COMMENT_MARKER ';'
#define MACRO_START "macr"
#define MACRO_END "endmacr"
#define MEMORY_ADDRESS_START 100

/* Used to mask MIB in an unsigned short (to simulate a 15bit CPU) */
#define BIT_MASK 0x8000

typedef enum OPERATION_CODES {
    MOV = 0,
    CMP,
    ADD,
    SUB,
    LEA,
    CLR,
    NOT,
    INC,
    DEC,
    JMP,
    BNE,
    RED,
    PRN,
    JSR,
    RTS,
    STOP
} OPERATION_CODES;

typedef enum ADDRESSING_CODE {
    NONE_ADDRESS_METHOD = 0,
    IMMEDIATE_ADDRESSING = 1,
    DIRECT_ADDRESSING = 2,
    INDIRECT_REGISTER = 4,
    DIRECT_REGISTER = 8
} ADDRESSING_CODE;

typedef enum ENCODING_TYPE {
    EXTERNAL = 1,
    RELOCATABLE = 2,
    ABSOLUTE = 4
} ENCODING_TYPE;

typedef enum OPERAND_POSITION {
    NONE_OPERAND = -1,
    DESTINATION_OPERAND,
    SOURCE_OPERAND
} OPERAND_POSITION;

/* OFFSET OF BITS IN A WORD, RIGHT TO LEFT */
#define OPERATION_CODE_OFFSET 11
#define DESTINATION_OPERAND_CODE_OFFSET 3
#define SOURCE_OPERAND_CODE_OFFSET 7
#define SOURCE_REGISTER_CODE_OFFSET 6
#define DESTINATION_REGISTER_CODE_OFFSET 3

#endif
