int is_preserved(char *name, macro_list *macros, label_table *labels);
int is_operation(char* str);
int is_instraction(char* str);
int is_register(char* str);
int is_label(char* str);
int validate_string_data(char* str);
char* parse_string_data(char* str);
int is_in_list(char *name, char *list[]);
numeric_data* parse_numeric_data(char *str, numeric_data* values, char *error);
int validate_numaric(char* str);
